### ISSUE TITLE
selectable_events can return an empty sequence.

### ISSUE THREAD

**Issue by adielashrov** [bThink-BGU/BPpy#4]
Something I noticed.
If there are no possible selected events, random.choice will raise an exception.

https://github.com/bThink-BGU/BPpy/blob/c76a954f8033ebf659b492a98c802037348e332d/bppy/model/event_selection/simple_event_selection_strategy.py#L22

Example:
`import random

selectable_events = set()

print(type(selectable_events))

event = random.choice(tuple(selectable_events))`

**Comment by tomyaacov** [comment]
That is ok. Emptiness is checked in the select method.
